import type { Project } from '@/types/project'

export const allProjects: Project[] = [
  {
    id: 'starbucks-promo',
    title: 'Starbucks Billion Brand Promo',
    category: 'brand',
    thumbnail: '/thumbnails/starbucks.webp',
    previewVideo: '/videos/starbucks-preview.mp4',
    description: 'High-impact promo conveying the $98.34B brand through kinetic typography.',
    tags: ['Brand Promo', 'Kinetic Type', 'After Effects'],
    featured: true,
    date: '2024-03-15',
    views: 128,
    challenge: 'Convey a $98.34B brand value in under 30 seconds.',
    process: 'Kinetic typography timed to beat. Warm coffee tones.',
    result: '128 views, shared by client across social channels.',
    client: 'Starbucks KE',
    slug: 'starbucks-promo',
    url: '/work/starbucks-promo',
  },
  {
    id: 'jumia-campaign',
    title: 'Jumia E-commerce Campaign',
    category: 'ads',
    thumbnail: '/thumbnails/jumia.webp',
    previewVideo: '/videos/jumia-preview.mp4',
    description: 'Energetic, conversion-focused motion content with bold graphic identity.',
    tags: ['E-commerce', 'Social Ads', 'After Effects'],
    featured: true,
    date: '2024-02-10',
    views: 172,
    challenge: 'Drive click-through on a competitive platform.',
    process: 'Bold graphic frames, rapid-fire cuts at 2–3s intervals.',
    result: 'High-energy campaign that stands out in the feed.',
    client: 'Jumia KE',
    slug: 'jumia-campaign',
    url: '/work/jumia-campaign',
  },
  {
    id: 'reel-hook-series',
    title: 'Reel Hook Series',
    category: 'social',
    thumbnail: '/thumbnails/reels.webp',
    previewVideo: '/videos/reels-preview.mp4',
    description: 'Scroll-stopping Instagram Reel hooks with platform-native transitions.',
    tags: ['Reels', 'Short-Form', 'Hooks'],
    featured: false,
    date: '2024-01-20',
    views: 235,
    challenge: 'Stop the scroll in the first 1.5 seconds.',
    process: 'Hook-first design. Most arresting frame is always frame one.',
    result: 'Series averaging 2× completion rate vs baseline.',
    client: 'Various',
    slug: 'reel-hook-series',
    url: '/work/reel-hook-series',
  },
  {
    id: 'client-conversion',
    title: 'Client Conversion Videos',
    category: 'brand',
    thumbnail: '/thumbnails/client.webp',
    previewVideo: '/videos/client-preview.mp4',
    description: 'Polished testimonial and brand-story videos that move viewers from awareness to trust.',
    tags: ['Testimonial', 'Brand Story', 'Conversion'],
    featured: false,
    date: '2023-12-05',
    views: 147,
    challenge: 'Build trust and move viewers from cold awareness to warm intent.',
    process: 'Intentional pacing, warmer color grade, human-first framing.',
    result: 'Used in client sales funnels to improve conversion.',
    client: 'Various',
    slug: 'client-conversion',
    url: '/work/client-conversion',
  },
]
  /*{
    id: 'motion-typography',
    title: 'Motion Typography Reel',
    category: 'motion',
    thumbnail: '/thumbnails/motion.webp',
    previewVideo: '/videos/motion-preview.mp4',
    description: 'Bold kinetic typography reel showcasing advanced text animation.',
    tags: ['Motion', 'Typography', 'After Effects'],
    featured: false,
    date: '2023-11-18',
    views: 170,
    slug: 'motion-typography',
    url: '/work/motion-typography',
  },
  {
    id: 'product-reveal',
    title: 'Product Reveal Ad',
    category: 'ads',
    thumbnail: '/thumbnails/product.webp',
    previewVideo: '/videos/product-preview.mp4',
    description: 'Dynamic product reveal designed for social media conversion.',
    tags: ['Ads', 'Product', 'Social'],
    featured: false,
    date: '2023-10-30',
    views: 150,
    slug: 'product-reveal',
    url: '/work/product-reveal',
  },
  {
    id: 'brand-identity',
    title: 'Brand Identity Animation',
    category: 'motion',
    thumbnail: '/thumbnails/brand.webp',
    previewVideo: '/videos/brand-preview.mp4',
    description: 'Logo and brand animation package for a growing startup.',
    tags: ['Branding', 'Animation', 'Logo'],
    featured: false,
    date: '2023-10-01',
    views: 89,
    slug: 'brand-identity',
    url: '/work/brand-identity',
  },
  {
    id: 'social-media-pack',
    title: 'Social Media Content Pack',
    category: 'social',
    thumbnail: '/thumbnails/social.webp',
    previewVideo: '/videos/social-preview.mp4',
    description: 'Multi-format social content pack covering Stories, Reels, and Feed posts.',
    tags: ['Social', 'Pack', 'Multi-format'],
    featured: false,
    date: '2023-09-12',
    views: 184,
    slug: 'social-media-pack',
    url: '/work/social-media-pack',
  },
  {
    id: 'ad-campaign-cut',
    title: 'Ad Campaign Cut',
    category: 'ads',
    thumbnail: '/thumbnails/ad.webp',
    previewVideo: '/videos/ad-preview.mp4',
    description: 'Rapid-fire social ad cut optimised for 6-second attention windows.',
    tags: ['Ads', 'Short-form', 'Conversion'],
    featured: false,
    date: '2023-08-25',
    views: 51,
    slug: 'ad-campaign-cut',
    url: '/work/ad-campaign-cut',
  },
]*/